# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 713db545ef4c1b23582c375079c5926d5ee48d4ef81d82ee5e56d6fcd21407a550f56ec544698f30b2e30f4992f3167628f3bd3e8bf23fb23137e5ed6353502a

test:
  secret_key_base: e966cf579b95e775f0c984d6aa634b5501fb406e8b20d30adf1d7a4c2829b93f23eecc1f193c5310ed6c787df3169ed2ad77bc4442f61b96bb530e39ae0ad5ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 69833be5cfa88d542f444824bf94c0a3958c99cbdcd94650b9ec21880ef044c14eba5ebf6f04b628eddf066afe7021c6c0e52e033e016d299a8462cee486cd35
